version: "3"
services:
        server:
            container_name: cars-api
            restart: always
            build: .
            environment:
              - MONGO_URI=mongodb://mongodb:27017
              - TOKEN_SECRET=token-secret 
              - DB_NAME=carsdb
            ports:
              - "3000:3000"
            links:
              - mongodb
        mongodb:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27017:27017'